[2024-05-28T18:41:06.772+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork2_dag.task1 scheduled__2024-05-28T18:40:50+00:00 [queued]>
[2024-05-28T18:41:06.819+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork2_dag.task1 scheduled__2024-05-28T18:40:50+00:00 [queued]>
[2024-05-28T18:41:06.820+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T18:41:06.856+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task1> on 2024-05-28 18:40:50+00:00
[2024-05-28T18:41:06.869+0000] {standard_task_runner.py:60} INFO - Started process 3747 to run task
[2024-05-28T18:41:06.881+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork2_dag', 'task1', 'scheduled__2024-05-28T18:40:50+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/fork_2.py', '--cfg-path', '/tmp/tmp1wsizcv1']
[2024-05-28T18:41:06.895+0000] {standard_task_runner.py:88} INFO - Job 188: Subtask task1
[2024-05-28T18:41:06.914+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T18:41:07.021+0000] {task_command.py:423} INFO - Running <TaskInstance: fork2_dag.task1 scheduled__2024-05-28T18:40:50+00:00 [running]> on host ac6c883b25f7
[2024-05-28T18:41:07.215+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork2_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T18:40:50+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T18:40:50+00:00'
[2024-05-28T18:41:07.217+0000] {logging_mixin.py:188} INFO - 0.9237714939046041
[2024-05-28T18:41:07.218+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T18:41:07.241+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork2_dag, task_id=task1, execution_date=20240528T184050, start_date=20240528T184106, end_date=20240528T184107
[2024-05-28T18:41:07.304+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T18:41:07.398+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
