[2024-05-28T19:11:51.505+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork3_dag.task3 scheduled__2024-05-28T19:11:10+00:00 [queued]>
[2024-05-28T19:11:51.668+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork3_dag.task3 scheduled__2024-05-28T19:11:10+00:00 [queued]>
[2024-05-28T19:11:51.676+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T19:11:52.063+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task3> on 2024-05-28 19:11:10+00:00
[2024-05-28T19:11:52.154+0000] {standard_task_runner.py:60} INFO - Started process 4928 to run task
[2024-05-28T19:11:52.268+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork3_dag', 'task3', 'scheduled__2024-05-28T19:11:10+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/fork_3.py', '--cfg-path', '/tmp/tmp6egl9e84']
[2024-05-28T19:11:52.328+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask task3
[2024-05-28T19:11:52.526+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:11:53.012+0000] {task_command.py:423} INFO - Running <TaskInstance: fork3_dag.task3 scheduled__2024-05-28T19:11:10+00:00 [running]> on host ac6c883b25f7
[2024-05-28T19:11:54.298+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork3_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T19:11:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T19:11:10+00:00'
[2024-05-28T19:11:54.306+0000] {logging_mixin.py:188} INFO - 0.9954437404023713
[2024-05-28T19:11:54.315+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T19:11:54.375+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork3_dag, task_id=task3, execution_date=20240528T191110, start_date=20240528T191151, end_date=20240528T191154
[2024-05-28T19:11:54.539+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T19:11:54.670+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
