[2024-05-28T18:43:07.150+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:42:40+00:00 [queued]>
[2024-05-28T18:43:07.191+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:42:40+00:00 [queued]>
[2024-05-28T18:43:07.192+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T18:43:07.293+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task2> on 2024-05-28 18:42:40+00:00
[2024-05-28T18:43:07.316+0000] {standard_task_runner.py:60} INFO - Started process 3903 to run task
[2024-05-28T18:43:07.351+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork2_dag', 'task2', 'scheduled__2024-05-28T18:42:40+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/fork_2.py', '--cfg-path', '/tmp/tmphix5iwm9']
[2024-05-28T18:43:07.354+0000] {standard_task_runner.py:88} INFO - Job 224: Subtask task2
[2024-05-28T18:43:07.420+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T18:43:07.601+0000] {task_command.py:423} INFO - Running <TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:42:40+00:00 [running]> on host ac6c883b25f7
[2024-05-28T18:43:08.068+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork2_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T18:42:40+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T18:42:40+00:00'
[2024-05-28T18:43:08.070+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T18:43:08.071+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T18:43:08.149+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork2_dag, task_id=task2, execution_date=20240528T184240, start_date=20240528T184307, end_date=20240528T184308
[2024-05-28T18:43:08.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T18:43:08.396+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
