[2024-05-28T19:11:57.600+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:30+00:00 [queued]>
[2024-05-28T19:11:57.747+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:30+00:00 [queued]>
[2024-05-28T19:11:57.748+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T19:11:57.900+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task1> on 2024-05-28 19:11:30+00:00
[2024-05-28T19:11:57.938+0000] {standard_task_runner.py:60} INFO - Started process 4933 to run task
[2024-05-28T19:11:57.971+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork3_dag', 'task1', 'scheduled__2024-05-28T19:11:30+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/fork_3.py', '--cfg-path', '/tmp/tmp3jw2374e']
[2024-05-28T19:11:57.974+0000] {standard_task_runner.py:88} INFO - Job 258: Subtask task1
[2024-05-28T19:11:58.030+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:11:58.163+0000] {task_command.py:423} INFO - Running <TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:30+00:00 [running]> on host ac6c883b25f7
[2024-05-28T19:11:58.355+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork3_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T19:11:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T19:11:30+00:00'
[2024-05-28T19:11:58.357+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T19:11:58.358+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T19:11:58.389+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork3_dag, task_id=task1, execution_date=20240528T191130, start_date=20240528T191157, end_date=20240528T191158
[2024-05-28T19:11:58.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T19:11:58.729+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
