[2024-05-28T18:41:32.650+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:41:10+00:00 [queued]>
[2024-05-28T18:41:32.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:41:10+00:00 [queued]>
[2024-05-28T18:41:32.729+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T18:41:32.887+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task2> on 2024-05-28 18:41:10+00:00
[2024-05-28T18:41:32.931+0000] {standard_task_runner.py:60} INFO - Started process 3789 to run task
[2024-05-28T18:41:32.953+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork2_dag', 'task2', 'scheduled__2024-05-28T18:41:10+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/fork_2.py', '--cfg-path', '/tmp/tmp5etgfi0r']
[2024-05-28T18:41:32.957+0000] {standard_task_runner.py:88} INFO - Job 197: Subtask task2
[2024-05-28T18:41:33.018+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T18:41:33.176+0000] {task_command.py:423} INFO - Running <TaskInstance: fork2_dag.task2 scheduled__2024-05-28T18:41:10+00:00 [running]> on host ac6c883b25f7
[2024-05-28T18:41:33.515+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork2_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T18:41:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T18:41:10+00:00'
[2024-05-28T18:41:33.518+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T18:41:33.519+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T18:41:33.539+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork2_dag, task_id=task2, execution_date=20240528T184110, start_date=20240528T184132, end_date=20240528T184133
[2024-05-28T18:41:33.638+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T18:41:33.739+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
